# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top_design_ct.xdc

# IP: ip/charLib/charLib.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==charLib || ORIG_REF_NAME==charLib} -quiet] -quiet
