# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Owner/Documents/School/ECE_524/Projects/Digital_Clock/Digital_clock/Digital_clock.cache/wt [current_project]
set_property parent.project_path C:/Users/Owner/Documents/School/ECE_524/Projects/Digital_Clock/Digital_clock/Digital_clock.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Owner/Documents/School/ECE_524/Projects/Digital_Clock/Digital_clock/Digital_clock.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/Owner/Documents/School/ECE_524/Projects/Digital_Clock/Digital_clock/Digital_clock.srcs/characterLib.coe
read_vhdl -library xil_defaultlib {
  C:/Users/Owner/Documents/School/ECE_524/Projects/Digital_Clock/Digital_clock/Digital_clock.srcs/sources_1/new/Binary_bcd.vhd
  C:/Users/Owner/Documents/School/ECE_524/Projects/Digital_Clock/Digital_clock/Digital_clock.srcs/sources_1/new/Debounce.vhd
  C:/Users/Owner/Documents/School/ECE_524/Projects/Digital_Clock/Digital_clock/Digital_clock.srcs/sources_1/imports/sources_1/imports/PmodOLED_Source/Delay.vhd
  C:/Users/Owner/Documents/School/ECE_524/Projects/Digital_Clock/Digital_clock/Digital_clock.srcs/sources_1/imports/sources_1/new/package_state_machine.vhd
  C:/Users/Owner/Documents/School/ECE_524/Projects/Digital_Clock/Digital_clock/Digital_clock.srcs/sources_1/new/Digital_clk.vhd
  C:/Users/Owner/Documents/School/ECE_524/Projects/Digital_Clock/Digital_clock/Digital_clock.srcs/sources_1/imports/sources_1/imports/PmodOLED_Source/OledExample.vhd
  C:/Users/Owner/Documents/School/ECE_524/Projects/Digital_Clock/Digital_clock/Digital_clock.srcs/sources_1/imports/sources_1/imports/PmodOLED_Source/OledInit.vhd
  C:/Users/Owner/Documents/School/ECE_524/Projects/Digital_Clock/Digital_clock/Digital_clock.srcs/sources_1/imports/sources_1/imports/PmodOLED_Source/PmodOLEDCtrl.vhd
  C:/Users/Owner/Documents/School/ECE_524/Projects/Digital_Clock/Digital_clock/Digital_clock.srcs/sources_1/imports/sources_1/imports/PmodOLED_Source/SpiCtrl.vhd
  C:/Users/Owner/Documents/School/ECE_524/Projects/Digital_Clock/Digital_clock/Digital_clock.srcs/sources_1/imports/sources_1/new/UART_rx.vhd
  C:/Users/Owner/Documents/School/ECE_524/Projects/Digital_Clock/Digital_clock/Digital_clock.srcs/sources_1/new/alarm_sound.vhd
  C:/Users/Owner/Documents/School/ECE_524/Projects/Digital_Clock/Digital_clock/Digital_clock.srcs/sources_1/new/clk_divider.vhd
  C:/Users/Owner/Documents/School/ECE_524/Projects/Digital_Clock/Digital_clock/Digital_clock.srcs/sources_1/new/Top_design.vhd
}
read_ip -quiet C:/Users/Owner/Documents/School/ECE_524/Projects/Digital_Clock/Digital_clock/Digital_clock.srcs/sources_1/ip/charLib/charLib.xci
set_property used_in_implementation false [get_files -all c:/Users/Owner/Documents/School/ECE_524/Projects/Digital_Clock/Digital_clock/Digital_clock.srcs/sources_1/ip/charLib/charLib_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Owner/Documents/School/ECE_524/Projects/Digital_Clock/Digital_clock/Digital_clock.srcs/constrs_1/new/top_design_ct.xdc
set_property used_in_implementation false [get_files C:/Users/Owner/Documents/School/ECE_524/Projects/Digital_Clock/Digital_clock/Digital_clock.srcs/constrs_1/new/top_design_ct.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Top_design -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_design.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_design_utilization_synth.rpt -pb Top_design_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
